server:
  port: 4001
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: ${user.dir}/springcloud-config/config-file/123
          search-paths: {application}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka